MBM/MBM/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('members.urls')),
    path('employee/',include('employee.urls')),
    path('blog/',include('mublog.urls')),
    path('news/', include('news.urls'))
]

MBM/employee/urls.py
from django.urls import path
from .views import EmployeeList, EmployeeDetailView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView

app_name = 'employee'

urlpatterns = [
    path('employee/', EmployeeList.as_view(), name='employee-list'),
    path('<int:id>/', EmployeeDetailView.as_view(), name='employee_detail'),
    path('new/', EmployeeCreateView.as_view(), name='employee-create'),
    path('employee/<pk>/update-employee/', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee/<pk>/delete-employee/', EmployeeDeleteView.as_view(), name='employee-delete'),

]

MBM/employee/models.py
from django.db import models
from django.urls import reverse


class Employee(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    birth_date = models.DateTimeField()
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    zip = models.CharField(max_length=5)
    title = models.CharField(max_length=30, blank=True)
    employee_id = models.CharField(max_length=10)
    start_date = models.DateTimeField()
    department = models.CharField(max_length=50)
    work_location = models.CharField(max_length=50)
    supervisor = models.CharField(max_length=50)
    emergency_contact_name = models.CharField(max_length=50)
    emergency_contact_number = models.CharField(max_length=50)
    salary = models.FloatField(default="$0.00", blank=True)
    phone_number = models.CharField(max_length=250, blank=True)
    email_address = models.CharField(max_length=30)
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)


    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('employee:employee_detail', args=[str(self.id)])

MBM/employee/views.py
from django.shortcuts import render
from .models import Employee
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views here.
class EmployeeList(ListView):
    model = Employee
    queryset = Employee.objects.all()
    template_name = 'employee/employee-list.html'

    def get_queryset(self):
        result = super(EmployeeList, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(first_name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(email_address__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(city__icontains=q) for q in query_list))
            )

        return result

class EmployeeDetailView(DetailView):
    template_name = "employee/employee_detail.html"
    member = Employee.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Employee, id=id_)


class EmployeeCreateView(CreateView):
    model = Employee
    fields = ['first_name', 'last_name','address','city','birth_date',
    'state','zip','phone_number','email_address','title','start_date','salary',
    'department','work_location','supervisor','emergency_contact_name','emergency_contact_number',
    ]

class EmployeeUpdateView(UpdateView):
    model = Employee
    fields = ['first_name', 'last_name','address','city',
    'state','zip','phone_number','email_address','title',
    'department','work_location','supervisor','emergency_contact_name','emergency_contact_number',
    ]

    def get_absolute_url(self):
        return reverse('employee:Employee_detail', args=[str(self.id)])

class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = '/portal/'

MBM/employee/templates/employee/employee_confirm_delete.html
{% extends 'members/base.html' %}

{% block body %}

<h2>MBM Delete Employee</h2>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

MBM/employee/templates/employee/employee_detail.html
{% extends "members/base.html" %}

{% block body %}

<a class="btn btn-warning btn-sm" href="{% url 'employee:employee-update' employee.id %}" type="button" name="button">Edit</a>
<a class="btn btn-danger btn-sm" href="{% url 'employee:employee-delete' pk=employee.id %}" type="button" name="button">Delete</a>


  <h1>{{ employee.first_name }} {{ employee.last_name}}</h1>

  <p><strong>Address:</strong>{{employee.address }}</p> <!-- author detail link not yet defined -->
  <p><strong>City:</strong> {{ employee.city }}</p>
  <p><strong>State:</strong> {{ employee.state }}</p>
  <p><strong>Phone:</strong> {{ employee.phone_number }}</p>
  <p><strong>Email:</strong> {{ employee.email_address }}</p>

    <a class="btn btn-secondary btn-sm" href="{% url 'employee:employee-list' %}" type="button" name="button">Back</a>
{% endblock %}

MBM/employee/templates/employee/employee_form.html
{% extends 'members/base.html' %}

{% block body %}

<h2>MBM Employee Portal</h2>
<div class="form-group">
  <form method="POST" enctype="multipart/form-data">
      <!-- Security token -->
      {% csrf_token %}
      <!-- Using the formset -->
      {{ form.as_p }}
      <input class="btn btn-primary bt-sm" type="submit" value="Submit">
      <a class="btn btn-secondary" href="{% url 'employee:employee-list' %}" type="button" name="button">Back</a>
  </form>
</div>

{% endblock %}

MBM/employee/templates/employee/employee_list.html
{% extends 'members/base.html' %}

{% block body %}

<h2>MBM Employee List</h2>

<a href="{% url 'employee:employee-create'%}" class="btn btn-primary btn-sm">Add Employee</a>
<table class="table table-hover table-sm mt-4" id="table">
  <thead>
    <tr>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Email</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
    </tr>
  </thead>
  <tbody>
    {% for mem in object_list %}
    <tr>
      <td><a href="{% url 'employee:employee_detail' mem.id %}">{{mem.first_name}}</a></td>
      <td><a href="{% url 'employee:employee_detail' mem.id %}">{{mem.last_name}}</a></td>
      <td><a href="{% url 'employee:employee_detail' mem.id %}">{{mem.email_address}}</a></td>
      <td><a href="{% url 'employee:employee_detail' mem.id %}">{{mem.city}}</a></td>
      <td><a href="{% url 'employee:employee_detail' mem.id %}">{{mem.state}}</a></td>
    </a>
    </tr>
    {% endfor  %}
</table>
<br class="mb-6">

{% endblock %}

MBM/employee/templates/employee/index.html
{% extends 'members/base.html' %}

{% block body %}

<h2>MBM Portal</h2>
  <hr class="mb-4">
<div class="container">
  <div class="row">
    <div class="col-sm">
      <h4>Employees</h4>
      <ul class="list-group">
  <li class="list-group-item"><a href="{% url 'employee:employee-create'%}">Add New Employee</a></li>
  <li class="list-group-item"><a href="{% url 'employee:employee-list'%}">View/Edit Employee</a></li>
  <li class="list-group-item">Import Employees</li>
  <li class="list-group-item">Timesheet</li>
  <li class="list-group-item">Reports</li>
</ul>
    </div>
    <div class="col-sm">
      <h4>Clients</h4>
      <ul class="list-group">
  <li class="list-group-item">Add New Client</li>
  <li class="list-group-item">View/Edit Clients</li>
  <li class="list-group-item">Import Clients</li>
  <li class="list-group-item">Projects</li>
  <li class="list-group-item">Reports</li>
</ul>
    </div>
    <div class="col-sm">
      <h4>IT</h4>
      <ul class="list-group">
        <li class="list-group-item">Create a Ticket</li>
        <li class="list-group-item">View/Edit Tickets</li>
        <li class="list-group-item">Request Access</li>
        <li class="list-group-item">Inventory</li>
        <li class="list-group-item">Reports</li>
</ul>
    </div>
  </div>
</div>
<hr class="mb-4">

<br class="mb-6">

{% endblock %}