MBM/MBM/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('members.urls')),
    path('employee/',include('employee.urls')),
    path('blog/',include('mublog.urls')),
    path('news/', include('news.urls'))
]

MBM/members/urls.py
from django.urls import path
from django.urls import re_path
from .views import MemberList, MemberDetailView, index,program,founders, MemberCreateView, MemberUpdateView, MemberDeleteView, signup,about,contact, employee_portal
from django.contrib.auth.decorators import login_required


app_name = 'members'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('about/', about, name='about'),
    path('contact/', contact,name='contact'),
    path('members/', MemberList.as_view(), name='member-list'),
    path('<int:id>/', MemberDetailView.as_view(), name='members_detail'),
    path('create/', MemberCreateView.as_view(), name='member-create'),
    path('<int:id>/update/', MemberUpdateView, name='member-update'),
    path('members/<pk>/delete/', MemberDeleteView.as_view(), name='member-delete'),
    path('portal/', employee_portal, name='portal'),
    path('programs/', program, name='programs'),
    path('founders/', founders, name='founders')
    
]

MBM/mublog/urls.py
from . import views
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from mublog.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

app_name = 'mublog'

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
]

MBM/members/models.py
from django.db import models
from django.urls import reverse
from stream_django.activity import Activity
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Address(models.Model):
    street = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    zip = models.CharField(max_length=5)
    
    def __str__(self):
        return f"{self.street},{self.city},{self.state}"
    
    
class Membership(models.Model):
    id = models.AutoField(primary_key=True)
    is_active = models.BooleanField(default=True)
    is_donor = models.BooleanField(default=False)
    is_volunteer = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    date_joined = models.DateField(auto_now_add=True)


class Member(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    date_of_birth = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=250, blank=True)
    email_address = models.CharField(max_length=30)
    date_created = models.DateField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    # membership = models.OneToOneField(Membership, on_delete=models.CASCADE)
    address = models.ManyToManyField(Address)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self): 
        return reverse('members:members_detail', args=[str(self.id)])

class Contact(models.Model):
    subject = models.CharField(max_length=100)
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=15)
    message = models.CharField(max_length=500)
    from_email = models.EmailField(max_length=15)
    
    def __str__(self):
        return self.name

MBM/members/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from .models import Address, Member, Contact

class MemberUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Member
        fields = ['first_name','last_name']
  
def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')      

class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    forcefield = forms.CharField(required=False, widget=forms.HiddenInput,label="Leave empty", validators=[should_be_empty])
  
    
    class Meta:
        model = Contact
        fields = "__all__"
       

MBM/members/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Member, Address, Membership
from django.urls import reverse,reverse_lazy
from django.contrib.auth.models import User
from mublog.models import Post
from .forms import MemberUpdateForm, ContactForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.contrib.auth import update_session_auth_hash
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.conf import settings


def index(request):
    post = Post.objects.filter(status=1).order_by('-created_on')
    page = request.GET.get('page', 1)

    paginator = Paginator(post, 2)
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)

    context = {'post':post}
    return render(request,'members/index.html',context)


def about(request):
    return render(request, 'members/about.html')

def program(request):
    return render(request, 'members/programs.html')

def founders(request):
    return render(request, 'members/founders.html')

def contact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'Subject: {form.cleaned_data["subject"]}'
            message = f'Message: {form.cleaned_data["message"]}'
            from_email = "no-reply@silvercityuprising.org"
            to = ['support@silvercityuprising.org',]
            name = form.cleaned_data["name"]
            email = f'Email: {form.cleaned_data["email"]}'
            
            try:
                send_mail(subject, message, from_email, to,name,email)
            
                return render(request,'members/contact.html',{'name':name})
            except BadHeaderError:
                return HttpResponse("Invalid headers")
        else:
            form = ContactForm()
            return HttpResponse("The header was invalid")
            
    return render(request, 'members/contact.html',{'form':form})


            
    
    
 

def signup(request):
    return render(request, 'members/member_signup.html')

def employee_portal(request):
    return render(request,'employee/index.html')

class MemberList(ListView):
    model = Member
    model = Address
    queryset = Member.objects.all()
    address = Address.objects.all()
    template_name = 'members/member_list.html'


class MemberDetailView(DetailView):
    template_name = "members/member_detail.html"
    member = Member.objects.all()
    form_class = MemberUpdateForm

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Member, id=id_)

    def form_valid(self,form):
        return super().form_valid(form)


class MemberCreateView(CreateView):
    model = Member
    fields = ['first_name', 'last_name','phone_number','email_address',
    ]
    
@login_required
class MemberUpdateView(UpdateView):
    model = Member
    fields = ['first_name', 'last_name','email_address',
    ]

class MemberDeleteView(DeleteView):
    model = Member
    success_url = '/members/'




    

MBM/members/templates/members/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@1,900&display=swap" rel="stylesheet">
  <script src="https://unpkg.com/scrollreveal"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>SCU</title>

</head>
<body>
  <div class="container-fluid">
    <!-- navbar start -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-default navbar-right">
      <!-- <img src="{% static 'img/brand.png' %}" width="30" height="30" alt=""> -->
      <a class="navbar-brand" href="/">SCU</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <!-- <a class="nav-item nav-link" href="{% url 'members:member-list'%}">Members</a> -->
          <a class="nav-item nav-link text-dark font-weight-bold" href="/programs/">Our Programs</a>
          <a class="nav-item nav-link text-dark font-weight-bold" href="/news/">News</a>
          <li class="nav-item nav-link dropdown ">
            <a class="dropdown-toggle text-dark font-weight-bold text-decoration-none" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              About
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item font-weight-bold" href="/about/">What we do</a>
              <a class="dropdown-item font-weight-bold" href="/founders/">Our Staff</a>
            </div>
          </li>
          <a class="nav-item nav-link text-dark font-weight-bold" href="/contact/">Contact</a>
          <!-- <a class="nav-item nav-link" href="#">Donate</a> -->
          <!-- <a class="nav-item nav-link" href="/portal/">Employee Portal</a> -->
          <!-- <a class="nav-item nav-link" href="{% url 'mublog:home' %}">Blog</a> -->
        </div>
        </div>
    </nav>
  </div>
  
    <!-- navbar end -->
  
    {% block body %}
    
    {% endblock %}

    <style>
      #footer {
        background: black;
        color: white;
        text-align: center;
      }
    </style>

    <section id="footer">
      <div class="row">
        <div class="container-fluid">
      <footer class="pt-4 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <!-- <img class="mb-2" src="{% static 'img/brand.png'%}" alt="" width="24" height="24"> -->
            <small class="d-block mb-3 text-muted">&copy;SCU 2020</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Announcements</a></li>
              <li><a class="text-muted" href="#">News</a></li>
              <li><a class="text-muted" href="#">Fundraising</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
      </div>
    </div>
    </section>

    

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" crossorigin="anonymous"></script>


</body>

</html>

MBM/members/templates/members/contact.html
{% extends 'members/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

<style>
    .contact {
        margin-top: 100px;
    }
</style>

<section id="contact">
    <div class="jumbotron jumbotron-fluid contact"  style="color: #f8f9fa;font-weight: bolder;background: black;">
        <div class="container">
          <center><h1 class="display-4">Contact SCU</h1></center>
          <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
        </div>
      </div>
    <hr>
    

    {% if name %}
    <center>
        <h2>Thanks {{ name }}!</h2>
        <p>We received your message and will get back you soon.</p>
    </center>
    <br><br><br>
    {% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-2"></div>
            <div class="col-md-4 col-sm-4">
                  <!--Section heading-->
    <!-- <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2> -->
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will get back to you within
        24-48 hours to assist you.</p>

        <form action="" method="post" class="mb-3">
            {% csrf_token %}
            {{form|crispy}}
            <!-- {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.errors}}
                <label>{{field.label_tag}}</label>
                <p>{{field}}</p>
            </div>
            {%endfor%} -->
            <button class="btn btn-secondary" type="reset">Reset</button>
            <button class="btn btn-primary" type="submit">Send</button>
            
        </form>

            </div>
            <div class="col-md-6 text-center mt-5">
                <ul class="list-unstyled mb-0">
                    <li><i class="fa fa-map-marker" aria-hidden="true"></i>
                        <p>P.O. Box 432</p>
                        <p>Meriden, CT 06450, USA</p>
                    </li>
    
                    <li><i class="fa fa-phone" aria-hidden="true"></i>
                        <p>860-515-8755</p>
                    </li>
    
                    <li><i class="fa fa-envelope" aria-hidden="true"></i>
                        <p>info@silvercityuprising.org</p>
                    </li>
                    <li>
                        <img src="{% static 'img/shirt.jpg' %}" style="height: 298px;width: 320px;border: 6px solid green;" alt="">
                    </li>
                </ul>
                </div>
            </div>
       </div> 
       {% endif %}
       </div>        
</section>


{% endblock %}

MBM/members/templates/members/index.html
{% extends 'members/base.html' %}

{% block body %}
{% load static %}
{% load activity_tags %}

<style>
 .fa {
  padding: 20px;
  font-size: 30px;
  width: 80px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;
}
.fa-facebook {
  background: #3B5998;
  color: white;
}

.fa-twitter {
  background: #55ACEE;
  color: white;
}

.fa-linkedin {
  background: #007bb5;
  color: white;
}

.fa-youtube {
  background: #bb0000;
  color: white;
}

.fa-instagram {
  background: #125688;
  color: white;
}
.fa:hover {
    opacity: 0.7;
}
#quotes {
  background: black;
  padding: 50px 0 30px 0;
  text-align: center;
  margin-top: 40px;
}
#quotes p {
  color: #fff;
  font-size: 32px;
  font-family: 'Josefin Sans';
}
#quotes p.author {
  font-size: 20px;
  color: #666;
}
#showcase img {
  height: 500px;
}
.showcase-left{
  margin-left: 200px;
  margin-top: 100px;
}
.showcase-right {
  margin-right: 200px;
}
.showcase-btn {
  margin-left: 242px;
  margin-top: 14px;
}
#info1 .info-right{
  margin-top: 90px;
}
.info-left img{
  margin-top: 90px;
  height: 400px;
  background-size: cover;
}
#info2 {
  margin: 20px 0 60px 0;
}
#member {
  /* background: url("{% static 'img/shirt.jpg'%}") no-repeat center center fixed; */
  padding: 40px;
  color: #fff;
  border-top: red 7px solid;
  border-bottom: green 7px solid;
  background-size: cover;
  background-color: black;
}
h1,h2,h3,h4,h5,h6 {
  font-family: 'Alegreya', serif;

}
p {
  font-family: Roboto;
}
#showcase h1{
  font-size: 63px;
  margin-bottom: 20px;
}
</style>
 
<section id="showcase">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="showcase-left">
          <h1>SILVER</h1>
          <H1>CITY</H1>
          <H1>UPRISING</H1>
          <hr>
          <h2>CORPORATION</h2>
        </div>
        <a class="btn btn-danger btn-lg showcase-btn" href="">Our Mission</a>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="showcase-right">
          <img src="{% static 'img/SCU.png' %}" alt="">
        </div>
      </div>
    </div>
  </div>
</section>

<section id="quotes">
  <div class="container">
    <p>“If not us, then who?
      If not now, then when?”</p>
    <p class="author">~John Lewis</p>
  </div>
</section>

<section id="info1">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="info-left">
          <img src="{% static 'img/blm.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="info-right">
          <h2>Silver City Uprising's Mission</h2>
          <p>"To create, build and promote healthy thriving businesses within the community, to positively contribute to the economic empowerment, growth and development of our community for this generation and future generations."</p>
          <br>
          <a class="btn btn-success btn-lg" href="">Read More</a>
        </div>
      </div>
    </div>
  </div>
</section>

<hr>

<section id="info2">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="info-left">
          <h2>Person Highlight of the month</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque labore quod similique deleniti est, iste recusandae laudantium libero vero molestias laboriosam consequatur cumque dolor commodi possimus nulla. Doloribus, ut. Non.</p>
          <div>
            {% for posts in post.first%}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ posts.title }}</h2>
                    <p class="card-text text-muted h6">{{ posts.author }} | {{ posts.created_on}} </p>
                    <p class="card-text">{{posts.content|slice:":200" }}</p>
                    <a href="{% url 'mublog:post_detail' posts.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
          </div> 
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="info-right">
          <h2>Business Highlight of the month</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque labore quod similique deleniti est, iste recusandae laudantium libero vero molestias laboriosam consequatur cumque dolor commodi possimus nulla. Doloribus, ut. Non.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container">

    <center><h1>Become A Member Today!</h1></center>
 
</div>

<section id="member">
  
  <div class="container">
      <div class="row">
          <div class="col-md-5 col-sm-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

              <!--Grid row-->
              <div class="row">

                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                          <input type="text" id="name" name="name" class="form-control">
                          <label for="name" class="">first name</label>
                      </div>
                      <div class="md-form mb-0">
                        <input type="text" id="name" name="name" class="form-control">
                        <label for="name" class="">last name</label>
                    </div>
                    <div class="md-form mb-0">
                      <input type="text" id="email" name="email" class="form-control">
                      <label for="email" class="">Your email</label>
                  </div>
                  </div>
                  <!--Grid column-->

              </div>
              <!--Grid row-->

              <div class="text-center text-md-left">
                <a class="btn btn-primary">Join Us</a>
            </div>
            <div class="status"></div>
        
          </form>
          </div>
          <div class="col-md-7 col-sm-7">
            <p style="font-size: 27px;">You will become a part of the movement to see change in our community by using all our efforts and resources to rebuild,
               uplift and educate our youths or adults who may need assistance.  Join now!</p>
          </div>
      </div>
  </div>
</section>

<section class="mb-2">
  <center>
    <h1>Follow Us!</h1>
                <br>
                <a href="#" class="fa fa-facebook"></a>
                <!-- <a href="#" class="fa fa-twitter"></a> -->
                <a href="#" class="fa fa-linkedin"></a>
                <a href="#" class="fa fa-youtube"></a>
                <a href="#" class="fa fa-instagram"></a>
  </center>
</section>

<!-- <section class="mt-4 mb-4" id="events">
  <center><h1>Events</h1></center>
  <hr>
  <center><h4>No current events.  Please check back later.</h4></center>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'img/ladies.jpg' %}" alt="First slide">
      <div class="container">
              <div class="carousel-caption text-left">
                <h1 id="header">SU</h1>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Become a member today!</a></p>
              </div>
            </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/shirt.jpg' %}" alt="Second slide">
      <div class="container">
              <div class="carousel-caption text-left">
                <h1 id="header">SU</h1>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Join the movement!</a></p>
              </div>
            </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/guys.jpg' %}" alt="Third slide">
      <div class="container">
              <div class="carousel-caption text-left">
                <h1 id="header">SU</h1>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Make a difference!</a></p>
              </div>
            </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</section> -->

<!-- BLOG SECTION -->
<!-- <br class="mb-3">
<div class="container">
  <div class="row blog">
  <div class="col-8">
    <h4>Latest blogs</h4>
    <hr>
    <div>
      {% for posts in post%}
      <div class="card mb-4">
          <div class="card-body">
              <h2 class="card-title">{{ posts.title }}</h2>
              <p class="card-text text-muted h6">{{ posts.author }} | {{ posts.created_on}} </p>
              <p class="card-text">{{posts.content|slice:":200" }}</p>
              <a href="{% url 'mublog:post_detail' posts.slug  %}" class="btn btn-primary">Read More &rarr;</a>
          </div>
      </div>
      {% endfor %}
    </div> -->
   
<script>
  window.sr = ScrollReveal();
  sr.reveal('.navbar', {
    duration:2000,
    origin:'left',
  });
  sr.reveal('.showcase-left', {
    duration:2000,
    origin:'top',
    distance:'300px',
  });
  sr.reveal('.showcase-right', {
    duration:2000,
    origin:'right',
    distance:'300px',
  });
  sr.reveal('.showcase-btn', {
    duration:2000,
    delay:1000,
    origin:'bottom',
    distance:'300px',
  });
  sr.reveal('#quotes div', {
    duration:2000,
    origin:'bottom',
  });
  sr.reveal('.info-left', {
    duration:2000,
    origin:'left',
    distance:'300px',
    viewFactor:0.2
  });
  sr.reveal('.info-right', {
    duration:2000,
    origin:'right',
    distance:'300px',
    viewFactor:0.2
  });
</script>

<!-- <span>Photo by <a href="https://unsplash.com/@thenewmalcolm?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Obi Onyeador</a> on <a href="https://unsplash.com/s/photos/black-people?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span> -->
<!-- <span>Photo by <a href="https://unsplash.com/@capturedby_kiana?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Kiana Bosman</a> on <a href="https://unsplash.com/s/photos/happy-black-people?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span> -->
{% endblock %}

MBM/members/templates/members/member_detail.html
{% extends "members/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

    <a class="btn btn-secondary btn-sm" href="{% url 'members:member-list' %}" type="button" name="button">Back</a>

    <div class="container">    
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">  <h4 >Member Profile</h4></div>
           <div class="panel-body">
          <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
           <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
         
     
          </div>
          <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
              <div class="container" >
                <h2>{{member.first_name}} {{member.last_name}}</h2>
                {% if member.pro_member %}
                <p><i class="fa fa-star mr-1" aria-hidden="true"></i>Member Plus+</span></p>
                {% else %}
                <a class="btn btn-success btn-sm"  href="/signup/" >Become a Member</a>
                {% endif %}
                          
                          
              </div>
               <hr>
              <ul class="container details" >
                <li><p><span class="glyphicon glyphicon-user one" style="width:50px;"></span>{{member.user.address.state}}</p></li>
                <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>{{ member.user.email }}</p></li>
              </ul>
              <hr>
              <div class="col-sm-5 col-xs-6 tital " >Member since: {{ member.date_created}}</div>
              <form method="POST" enctype="multipart/form-data">
                <!-- Security token -->
                {% csrf_token %}
                <!-- Using the formset -->
                  {{form|crispy}}
                <button class="btn btn-primary bt-sm" type="submit" value="Submit">Update</button>
                <a class="btn btn-secondary" href="{% url 'members:member-list' %}" type="button" name="button">Back</a>
            </form>
          </div>
      </div>
  </div>
</div>
{% endblock %}

MBM/members/templates/members/member_form.html
{% extends 'members/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<h2>MBM Create Member Page</h2>
<div class="form-group">
  <form method="POST" enctype="multipart/form-data">
      <!-- Security token -->
      {% csrf_token %}
      <!-- Using the formset -->
      {{form|crispy}}
      <input class="btn btn-primary bt-sm" type="submit" value="Submit">
      <a class="btn btn-secondary" href="{% url 'members:member-list' %}" type="button" name="button">Back</a>
  </form>
</div>


{% endblock %}